(()=>{"use strict";
const LOCAL_COUNTIES=[{name:"Florence",code:"041",note:"Part of Florence County is in SC-07."},{name:"Darlington",code:"031",note:"SC-07"},{name:"Dillon",code:"033",note:"SC-07"},{name:"Marion",code:"067",note:"SC-07"},{name:"Marlboro",code:"069",note:"SC-07"}];
const LOCAL_SOURCES=[["U.S. Census Bureau","2024 ACS 5-year county data","https://data.census.gov/"],["SC-07 district source","District footprint and local project records","https://fry.house.gov/about/our-district.htm"],["SC-07 funding records","Local federal project records","https://fry.house.gov/services/fy26-community-project-funding.htm"]];
const escLocal=x=>String(x==null?"":x).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const moneyLocal=x=>x==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(x);
const numLocal=x=>x==null?"—":new Intl.NumberFormat("en-US").format(x);
const pctLocal=x=>x==null?"—":Number(x).toFixed(1)+"%";
async function localCommunity(code){const C=window.APP_CONFIG||{};if(!C.SUPABASE_URL)return null;const r=await fetch(C.SUPABASE_URL.replace(/\/$/,"")+"/functions/v1/census-data",{method:"POST",headers:{"Content-Type":"application/json","apikey":C.SUPABASE_PUBLISHABLE_KEY||""},body:JSON.stringify({action:"community",state:"45",county:code})});if(!r.ok)throw Error("Local Census request failed");return r.json()}

function localFocusShell(){
return "<section class='local-focus card' id='local-focus'>"+
"<div class='local-focus-head'><div><div class='eyebrow'>District focus</div><h2>South Carolina's 7th District, in actual numbers</h2><p>Real county data makes the local focus visible instead of treating South Carolina as a label.</p></div><div class='local-live-badge'><i></i> Live public data</div></div>"+
"<div class='local-county-grid' id='local-county-grid'>"+LOCAL_COUNTIES.map(c=>"<article class='local-county-card'><b>"+escLocal(c.name)+" County</b><span>"+escLocal(c.note)+"</span><div class='local-loading'>Loading 2024 ACS data…</div></article>").join("")+"</div>"+
"<div class='local-focus-foot'><span>Source: U.S. Census Bureau, 2024 ACS 5-year estimates.</span><button class='btn' data-nav='explore'>Open Community Explorer</button></div></section>"+
"<section class='local-how card'><div class='local-section-title'><div><div class='eyebrow'>The core workflow</div><h2>How CivicSignal Works</h2><p>Four steps explain the whole product.</p></div></div><div class='how-grid'>"+
"<div><b>01 · FIND</b><h3>Explore</h3><p>Explore local conditions and public data.</p></div><div><b>02 · REPORT</b><h3>Document</h3><p>Document an issue you see in your community.</p></div><div><b>03 · VERIFY</b><h3>Review</h3><p>A human reviewer checks community submissions.</p></div><div><b>04 · ACT</b><h3>Follow the pathway</h3><p>See relevant agencies, funding programs, meetings, and documented actions.</p></div></div></section>"+
"<section class='local-why card'><div class='local-section-title'><div><div class='eyebrow'>Why it exists</div><h2>Connect information that is usually separated</h2><p>CivicSignal is not trying to replace government websites. It connects their information with a verified community-report workflow.</p></div></div><div class='why-grid'><div><b>Existing source</b><span>Government data</span></div><div><b>CivicSignal</b><span>Government data + county context</span></div><div><b>Existing source</b><span>Maps</span></div><div><b>CivicSignal</b><span>Maps + verified local reports</span></div><div><b>Existing source</b><span>Agency information</span></div><div><b>CivicSignal</b><span>Agency information + civic pathway</span></div><div class='why-bridge'><b>Usually separated</b><span>One connected workflow: find → report → verify → understand who can address it.</span></div></div></section>"+
"<section class='local-tech card'><div class='local-section-title'><div><div class='eyebrow'>Technical architecture</div><h2>What I built</h2><p>The app is a JavaScript client connected to a real backend and public data services.</p></div></div><div class='arch'><div>Browser</div><span>↓</span><div>Leaflet / JavaScript</div><span>↓</span><div>Supabase</div><span>↓</span><div>PostgreSQL + RLS</div><span>↓</span><div>Edge Functions</div><span>↓</span><div>Government APIs</div></div><div class='tech-note'><b>Built in the project</b><span>County data loading, report submission, human verification, persistent civic events, interactive maps, evidence labeling, calculations, and the public Civic Action Pathway.</span></div></section>"+
"<section class='local-story card'><div class='local-section-title'><div><div class='eyebrow'>Local evidence</div><h2>One concrete issue is enough to demonstrate the system</h2><p>Flooding and stormwater are used as a local example because the app can connect an observed issue to public agencies and documented federal project records.</p></div><a class='btn primary' data-nav='report'>Start a report</a></div><div class='local-evidence'><b>Documented district example</b><span>Official SC-07 project records include stormwater work in Dillon County and Crooked Creek improvements in Marlboro County.</span><a href='https://fry.house.gov/services/fy26-community-project-funding.htm' target='_blank' rel='noopener'>Read the primary record</a></div></section>"+
"<section class='local-sources card'><div class='local-section-title'><div><div class='eyebrow'>Sources</div><h2>Primary sources used here</h2></div></div><div class='source-grid'>"+LOCAL_SOURCES.map(s=>"<a href='"+s[2]+"' target='_blank' rel='noopener'><b>"+escLocal(s[0])+"</b><span>"+escLocal(s[1])+"</span></a>").join("")+"</div></section>";
}
async function fillLocalData(){const grid=document.querySelector("#local-county-grid");if(!grid)return;const results=await Promise.allSettled(LOCAL_COUNTIES.map(c=>localCommunity(c.code)));grid.innerHTML=results.map((result,i)=>{const c=LOCAL_COUNTIES[i],d=result.status==="fulfilled"&&result.value?result.value.county:null;if(!d)return "<article class='local-county-card'><b>"+escLocal(c.name)+" County</b><span>"+escLocal(c.note)+"</span><div class='local-loading'>Data unavailable right now. Use Community Explorer to retry.</div></article>";const poverty=d.poverty_total?Number(d.poverty_under)/Number(d.poverty_total)*100:null;return "<article class='local-county-card'><b>"+escLocal(c.name)+" County</b><span>"+escLocal(c.note)+"</span><div class='local-metrics'><div><small>Population</small><strong>"+numLocal(d.population)+"</strong></div><div><small>Median income</small><strong>"+moneyLocal(d.median_income)+"</strong></div><div><small>Poverty</small><strong>"+pctLocal(poverty)+"</strong></div></div><button class='btn local-open-county' data-local-county='"+escLocal(c.code)+"'>Open county data</button></article>"}).join("");grid.querySelectorAll(".local-open-county").forEach(btn=>{btn.onclick=()=>{document.querySelector("[data-nav='explore']")?.click();setTimeout(()=>{const county=document.querySelector("#county");if(county){county.value=btn.dataset.localCounty;county.dispatchEvent(new Event("change",{bubbles:true}))}},80)}})}
function addLocalFocus(){if(document.querySelector(".local-focus"))return;const content=document.querySelector(".content");if(!content)return;const hero=content.querySelector(".home-hero,.hero");if(hero){const wrap=document.createElement("div");wrap.className="local-focus-marker";wrap.innerHTML=localFocusShell();hero.insertAdjacentElement("afterend",wrap);fillLocalData().catch(()=>{})}}
const observer=new MutationObserver(()=>{const app=document.querySelector("#app");if(!app)return;if(app.querySelector(".crumb")?.textContent?.includes("Overview"))addLocalFocus()});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(addLocalFocus,50);
})();